server/models/Deck.js
added to deck schema a boolean for public/private.  removed repeat fields from card schema
=> Deck schema server

server/controllers/ProfileController.js, server/main.js, server/services/ProfileService.js, server/services/UserService.js
=> added profile routes

client/src/App.vue, client/src/router/index.js, client/src/store/ProfileModule.js, client/src/store/index.js, client/src/views/Login.vue, client/src/views/Profile.vue
=> client profile view, some navbar

client/src/App.vue, client/src/main.js, client/src/store/ProfileModule.js, client/src/store/index.js, client/src/utils/NotificationService.js, client/src/views/Profile.vue, server/controllers/DeckController.js, server/controllers/UserController.js
=> More profile client stuff

client/src/App.vue, client/src/store/index.js, client/src/utils/NotificationService.js
=> added register

client/src/App.vue, client/src/store/ProfileModule.js, client/src/store/index.js, client/src/views/Profile.vue
we cleaned up profile page loads and are pushing public decks to the profile page. (todd has a public deck to view, rod doesn't)
=> Quick thursday morning fixes

client/src/components/NewDeck.vue, client/src/views/Home.vue
=> modifies scroll bar

client/src/views/Profile.vue
=> styled profile view

client/src/components/Rules.vue, client/src/store/DeckModule.js
updated some rules component functionality
=> Rules cont 

client/src/components/EditDeck.vue, client/src/views/DeckDetails.vue
slight modifications to DeckDetails
=> editDeck component linked to deckDetails view

client/src/components/CardDetails.vue
=> Edit form card detail modal

client/src/components/CardDetails.vue, client/src/store/CardModule.js, client/src/store/index.js, client/src/views/DeckDetails.vue, server/controllers/DeckController.js
Edit and Delete should be working for cards now
=> Edit card function

server/controllers/LobbyController.js, server/main.js, server/socket/SocketService.js
socket set up for moveCard in LobbyController
=> sets up sockets for back end

client/src/store/SocketModule.js, server/controllers/LobbyController.js
Sets up SocketModule in client
=> Backend sockets

client/public/index.html, client/src/App.vue, client/src/components/DeckSticker.vue, client/src/components/NewDeck.vue, client/src/views/Home.vue
sets body and app to 100vh, sets background image to our background image
=> Home styling contd

client/src/App.vue, client/src/components/Zone.vue, client/src/store/LobbyModule.js, client/src/store/SocketModule.js, client/src/store/index.js, server/controllers/LobbyController.js, server/main.js, server/socket/SocketService.js
sets up sockets for moving cards, adds notes
=> Player hand contd

server/controllers/DeckController.js, server/controllers/LobbyController.js, server/main.js, server/services/DeckService.js, server/services/LobbyService.js
adds comments to main.js in server, DeckController, DeckService, LobbyController, LobbyService, SocketService
=> Server comments

client/src/components/PlayerHand.vue, client/src/components/Zone.vue, client/src/store/LobbyModule.js, client/src/store/SocketModule.js, client/src/store/index.js, client/src/views/Lobby.vue, server/controllers/LobbyController.js, server/services/LobbyService.js
removed console logs, commented-out code (except for moveCard mutation
=> Jims branch

client/src/store/LobbyModule.js, client/src/store/SocketModule.js, client/src/views/Lobby.vue, server/controllers/LobbyController.js, server/socket/SocketService.js
updates client and server to emit and receive signals to notify clients of the deck being shuffled. SocketModule makes a single commit to the store mutation.
=> creates socket for shuffling cards

client/src/store/LobbyModule.js, client/src/store/SocketModule.js, client/src/store/index.js, client/src/views/Lobby.vue, server/controllers/LobbyController.js, server/services/LobbyService.js, server/socket/SocketService.js
=> can successfully shuffle cards through socket

client/src/components/CardSticker2.vue, client/src/components/PlayerHand.vue
sorry guys, my bad, I forgot to pass the zone to the player hand
=> last minute fixes

client/src/components/DeckSticker.vue
Adjusts color of DeckSticker to match NewDeck component, removes underline on hover.
=> removes routerLink underline, changes color
